on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: continuous-integration
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout sources
      - uses: actions/setup-node@v2
        name: Setup node 14
        with:
          node-version: '14'
      - uses: actions/setup-python@v1
        name: Setup python 3.9
        with: 
          python-version: "3.9"
      - name: Install build tools
        run: pip install build pytest flake8
      - run: npm install
        working-directory: client
        name: Install frontend dependencies
      - run: npm test
        working-directory: client
        name: Run client unit-tests
      - run: python -m build .
        name: Build package
      - run: python -m pytest
        name: Run server unit-tests
      - run: flake8 plsexplain
        name: Check Python code style
      - name: Build documentation
        run: make html
        working-directory: docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
        if: github.event_name != 'pull_request'
